# Generated by Django 5.0.2 on 2024-03-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="max_group_clients",
            new_name="max_group_students",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="min_group_clients",
            new_name="min_group_students",
        ),
    ]
